FROM node:14
ARG GITLAB_ACCESS_TOKEN

WORKDIR /app

ADD  ./package-lock.json ./package.json /app/

RUN npm config set @aave-tech:registry https://gitlab.com/api/v4/packages/npm/

RUN npm run load:npm
RUN npm ci

ADD ./ /app/
